<?php
require_once 'xajax_core/xajax.inc.php';  //THIS MUST BE DOWNLOADED FROM http://xajax.sourceforge.net/

// ENTER YOUR OWN DATABASE CONNECTION INFORMATION OR CHANGE THIS TO AN INCLUDE FOR YOUR INFORMATION
mysql_connect(" "," "," ");
mysql_select_db(" ");

// Start the XAJAX code lines to prepare the requests.
$xajax = new xajax();
$xajax->registerFunction("nextCategory");
//$xajax->processRequests();

// This function is called by the JavaScript to gather the necessary information.
function nextCategory($ecatid, $box) {
    //ecatid: category ID selected in the box.
    //box: this is the box that the category was selected in.
    global $shipconn;
    list($j, $boxnum) = explode("_", $box);
    $boxnum++; //increment the box to the next box.
    $newContent = "";
    
    // If this is a leaf category, popuplate the category field instead of a new box.
    $sql = "select LeafCategory from ebay_categories_test where CategoryID = $ecatid";
    list($leaf) = mysql_fetch_row(mysql_query($sql));
    
    if ($leaf) {
        $objResponse = new xajaxResponse();
        $objResponse->addAssign("FinalCat","value", $ecatid);
        return $objResponse->getXML();
    }
    
    // selecting the necessary information based on the Category that is being sent to the function.
    $sql = "select CategoryID, CategoryName, LeafCategory
            from ebay_categories_test where Expired = 0 and Virtual = 0 and CategoryParentID = $ecatid
            and CategoryParentID != CategoryID order by CategoryName";
    $getcats = mysql_query($sql);
    if (mysql_num_rows($getcats)) {  //if there are categories in here, create the selection box to be populated in the table field.
        $newContent .= "<select name=\"catbox_{$boxnum}\" "
                     . "onChange=\"xajax_nextCategory(this[this.selectedIndex].value, 'catbox_{$boxnum}')\" "
                     . "size=\"8\" style=\"width: 240px; height: 150px;\">\n";
        while (list($CategoryID, $CategoryName, $LeafCategory) = mysql_fetch_row($getcats)) {  //loop through and make options
            $newContent .= "        <option value=\"$CategoryID\">$CategoryName".(($LeafCategory)?"":"-->")."</option>\n";
        }
        $newContent .= "</select>\n";
    }
    $objResponse = new xajaxResponse();
    
    // add a command to the response to assign the innerHTML attribute of
    // the element with id="SomeElementId" to whatever the new content is
    $objResponse->addAssign("catbox_{$boxnum}","innerHTML", $newContent); //assign the selection box.
    $objResponse->addAssign("boxnum_{$boxnum}","innerHTML", "<b>{$boxnum}.</b>"); //assign the box number.
    for ($i = ($boxnum +1); $i < 7; $i++) {  //This resets all other boxes up to the 6th one in case one clicks on a previous box.
        $objResponse->addAssign("catbox_{$i}","innerHTML", "");
        $objResponse->addAssign("boxnum_{$i}","innerHTML", "");
    }    
    
    //return the XML response generated by the xajaxResponse object
    return $objResponse->getXML();
}

//show categories for the first box.
$sql = "select CategoryID, CategoryName, LeafCategory from ebay_categories_test where Expired = 0 and Virtual = 0 and CategoryParentID = CategoryID";
$getcats = mysql_query($sql);

?><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	<title>eBay Category Selector</title>
<? $xajax->printJavascript(); //this is required for the AJAX system to work. ?>
</head>
<body bgcolor="#FFFFFF">
<div align="center" style="font-size: 14pt">eBay Category Selector<br />Using AJAX</div>

<form method="post" action="">
<table cellpadding=3 cellspacing=0>
<tr valign=top>
    <td><b>1.</b></td>
    <td id="catbox_1"><select name="catbox_1" onClick="xajax_nextCategory(this[this.selectedIndex].value, 'catbox_1')" size="8" style="width: 240px; height: 150px;"><?
        while (list($CategoryID, $CategoryName, $LeafCategory) = mysql_fetch_row($getcats)) {
            echo "        <option value=\"$CategoryID\">$CategoryName".(($LeafCategory)?"":"-->")."</option>\n";
        }
    ?></select></td>
    <td id="boxnum_2"></td>
    <td id="catbox_2"></td>
</tr>

<tr valign=top>
    <td id="boxnum_3"></td>
    <td id="catbox_3"></td>
    <td id="boxnum_4"></td>
    <td id="catbox_4"></td>
</tr>

<tr valign=top>
    <td id="boxnum_5"></td>
    <td id="catbox_5"></td>
    <td id="boxnum_6"></td>
    <td id="catbox_6"></td>
</tr>
</table>

Category: #<input type="text" id="FinalCat" name="ecatid<? if ($secondaryCat) echo "2"; ?>" size=6> <input type="submit" name="action" value="Next"></div>
</form>
</body>
</html>
